name: Automerge Dependabot PRs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build_artifacts.yml
    with:
      buildVersion: "1.0.0.${{ github.run_number }}"
      nugetVersion: "1.0.0"
      publish: false
      debug: false
    secrets: inherit

  automerge:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: fastify/github-action-merge-dependabot@v3