name: Do Test

on:
  workflow_call:
  workflow_dispatch:

jobs:
  testing:
    name: Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Print username
        run: |
          echo "The GitHub Action Secret will be masked:  "
          echo ${{ secrets.DOCKERHUB_USERNAME }}
          echo "Trick to echo GitHub Actions Secret:  "
          echo ${{secrets.DOCKERHUB_USERNAME}} | sed 's/./& /g'