name: Do Test

on:
  workflow_call:

jobs:
  testing:
    name: Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Print username
        run: |
          echo "$user_name"
          echo "$env:user_name"
          echo "%user_name%"