name: Do Test

on:
  workflow_call:

jobs:
  testing:
    name: Testing
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Print username
        run: echo "The username is: ${{ secrets.DOCKERHUB_USERNAME }}"