name:  Publish To Docker Hub

on:
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Print username
        run: |
          echo "The GitHub Action Secret will be masked: "
          echo ${{ secrets.DOCKERHUB_USERNAME }}
          echo "Trick to echo GitHub Actions Secret: "
          echo ${{ secrets.DOCKERHUB_USERNAME }} | sed 's/./& /g'

      - name: Extract metadata (tags, labels) for Docker
        if: false  
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: nicolaihenriksen/smtptorest
      
      - name: Build and push Docker image
        if: false  
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}