name:  Publish Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version being released'
        required: true
        type: string

env:
  configuration: Release
  isRelease: false

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Build artifacts
        uses: ./.github/workflows/build_artifacts.yml
        with:
          isRelease: ${{ env.isRelease }}

      - name: Log in to Docker Hub
        if: ${{ env.isRelease }}
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        if: ${{ env.isRelease }}
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: nicolaihenriksen/smtptorest
      
      - name: Build and push Docker image
        if: ${{ env.isRelease }}
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./SmtpToRest.Docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}