name: Test workflow

on:
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

env:
  user_name: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  build:
    name: Build artifacts
    uses: ./.github/workflows/do_test.yml